
FILTER=png

all: clean-98.png kernel-98.png

clean-98.png:
	dia clean-98.dia --export=clean-98.$(FILTER) --filter=$(FILTER)

kernel-98.png:
	dia kernel-98.dia --export=kernel-98.$(FILTER) --filter=$(FILTER) 

